In [8]:
import pandas as pd

# Working with JSON

In [9]:
df = pd.read_json("/Users/apple/Desktop/AI-ML/Datasets/test.json")
df

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [10]:
df = pd.read_json("https://www.floatrates.com/daily/inr.json")
df

,aud,cad,chf,cny,eur,gbp,hkd,idr,jpy,krw,...,wst,xcd,xcg,xpf,yer,zmw,irr,lak,rub,syp
code,AUD,CAD,CHF,CNY,EUR,GBP,HKD,IDR,JPY,KRW,...,WST,XCD,XCG,XPF,YER,ZMW,IRR,LAK,RUB,SYP
alphaCode,AUD,CAD,CHF,CNY,EUR,GBP,HKD,IDR,JPY,KRW,...,WST,XCD,XCG,XPF,YER,ZMW,IRR,LAK,RUB,SYP
numericCode,036,124,756,156,978,826,344,360,392,410,...,882,951,532,953,886,967,364,418,643,760
name,Australian Dollar,Canadian Dollar,Swiss Franc,Chinese Yuan,Euro,U.K. Pound Sterling,Hong Kong Dollar,Indonesian Rupiah,Japanese Yen,South Korean Won,...,Samoan tala,East Caribbean Dollar,Caribbean guilder,CFP Franc,Yemeni rial,Zambian kwacha,Iranian rial,Lao kip,Russian Rouble,Syrian pound
rate,0.01490953,0.01471072,0.00849422,0.07089039,0.00909844,0.00780128,0.08239588,188.11409887,1.65765010,14.92898498,...,0.02837789,0.02836060,0.01880210,1.08600522,2.50197187,0.19982830,14465.36848449,237.58271875,0.84745290,1.28183731
date,"Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT",...,"Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT","Thu, 6 Aug 2026 15:55:19 GMT"
inverseRate,67.07121414,67.97762727,117.72709692,14.10628354,109.90898869,128.18413810,12.13652951,0.00531592,0.60326362,0.06698379,...,35.23870547,35.26019042,53.18554279,0.92080588,0.39968475,5.00429611,0.00006913,0.00420906,1.18000658,0.78013020